version: '3.8'  # Use a more current version if possible

name: prl

services:
  ubuntu:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: zdeneklapes/${COMPOSE_PROJECT_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tmp/fish/:/root/.local/share/fish/  # Persist fish shell history
      - ./tmp/tmp:/tmp/                       # Temporary files directory
      - ./:/app/                               # Application code
    stdin_open: true
    tty: true
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
